// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkWueho-U4xV94UiPHpBis7lKbbIStCi8',
    appId: '1:595593702877:web:f20a34ede10cd3cc8eda34',
    messagingSenderId: '595593702877',
    projectId: 'mesleki-asistan',
    authDomain: 'mesleki-asistan.firebaseapp.com',
    storageBucket: 'mesleki-asistan.firebasestorage.app',
    measurementId: 'G-E7DTN6T2MM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdvGy7Ms2ca4ItBKHa8lbkjqzEJNJMPPI',
    appId: '1:595593702877:android:89ab800713a11d688eda34',
    messagingSenderId: '595593702877',
    projectId: 'mesleki-asistan',
    storageBucket: 'mesleki-asistan.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBI2KNq1Q0cOtxHd78GKbGvcoxGZj6ck48',
    appId: '1:595593702877:ios:87035065e8470c648eda34',
    messagingSenderId: '595593702877',
    projectId: 'mesleki-asistan',
    storageBucket: 'mesleki-asistan.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBI2KNq1Q0cOtxHd78GKbGvcoxGZj6ck48',
    appId: '1:595593702877:ios:87035065e8470c648eda34',
    messagingSenderId: '595593702877',
    projectId: 'mesleki-asistan',
    storageBucket: 'mesleki-asistan.firebasestorage.app',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkWueho-U4xV94UiPHpBis7lKbbIStCi8',
    appId: '1:595593702877:web:c7ce7d1cb84f5fde8eda34',
    messagingSenderId: '595593702877',
    projectId: 'mesleki-asistan',
    authDomain: 'mesleki-asistan.firebaseapp.com',
    storageBucket: 'mesleki-asistan.firebasestorage.app',
    measurementId: 'G-HXEQNGWJM4',
  );
}
